{% set name = "dlib" %}
{% set version = "19.24.8" %}
{% set tag = "v" ~ ".".join(version.split(".")[:2]) %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9135900983e279b5e5d0b1bb31b684a3054ea4f3ea1b1c69e8a675659271003d

  patches:
    - lapack_sgetrf.patch      # [unix]
    - setup_cmake_args.patch
    - fix_libtools_error.patch  # [osx]
    - unvendor_pybind11.patch
    - use_new_cudatoolkit.patch  # [cuda_compiler_version != "None"]
    - allow_any_generator.patch

build:
  number: 0
  # xref: https://github.com/conda-forge/dlib-feedstock/issues/84
  skip: true  # [aarch64 and (cuda_compiler_version or "").startswith("12")]
  skip: true  # [win and cuda_compiler_version == "11.2"]

outputs:
  - name: {{ name }}
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      # weigh down cpu implementation and give cuda preference
      track_features:
        - dlib-cpu                               # [cuda_compiler_version in (undefined, "None")]
      run_exports:
        - {{ pin_subpackage('dlib', max_pin='x.x') }}
    script: build-pkg.sh  # [not win]
    script: bld-pkg.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
        - cmake
        - ninja
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
      host:
        - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None") != "None"]
        - cudnn                                  # [cuda_compiler_version != "None"]
        - nccl                                   # [cuda_compiler_version != "None" and linux]
        - libjpeg-turbo
        - libcblas  # [not win]
        - liblapack   # [not win]
        - libpng
        - numpy
        - pip
        - setuptools
        - pybind11
        - python
        - sqlite  # [not win]
        - cuda-cudart-dev                        # [(cuda_compiler_version or "").startswith("12")]
        - libcublas-dev                          # [(cuda_compiler_version or "").startswith("12")]
        - libcurand-dev                          # [(cuda_compiler_version or "").startswith("12")]
        - libcusolver-dev                        # [(cuda_compiler_version or "").startswith("12")]
      run:
        - python
        - __cuda                                 # [cuda_compiler_version != "None"]

    test:
      files:
        - test_data/face.jpg
        - test_data/face.png
        - test_data/images.xml
        # contains test configurations including some skips for missing fixtures
        - setup.cfg
      source_files:
        - tools/python/test
      requires:
        - more-itertools
        - pillow
        - pip
        - pytest>=7
        - pytest-azurepipelines
        - tqdm

      imports:   # [not (aarch64 and cuda_compiler_version != "None")]
        - dlib  # [not (aarch64 and cuda_compiler_version != "None")]

      commands:
        - python -m pip check
        - python -m pytest tools/python/test  # [not (aarch64 and cuda_compiler_version != "None")]

  # Help the linter to avoid errors on a package not having tests.
  {% set dlib_cpu_gpu = name + "-cpu" %}   # [cuda_compiler_version == "None"]
  {% set dlib_cpu_gpu = name + "-gpu" %}   # [cuda_compiler_version != "None"]
  - name: {{ dlib_cpu_gpu }}
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
    requirements:
      run:
        - {{ pin_subpackage('dlib', exact=True) }}
    # aarch64 test fails because of the GLIBC 2.28 issue, which only appears at test time.
    # xref https://github.com/conda-forge/conda-forge.github.io/issues/1941
    test:   # [not (aarch64 and cuda_compiler_version != "None")]
      imports:   # [not (aarch64 and cuda_compiler_version != "None")]
        - dlib  # [not (aarch64 and cuda_compiler_version != "None")]

about:
  home: http://dlib.net
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: toolkit for making real world machine learning and data analysis applications
  dev_url: https://github.com/davisking/dlib
  doc_source_url: https://github.com/davisking/dlib/tree/{{ tag }}/docs
  description: |-
    Dlib is a modern C++ toolkit containing machine learning algorithms and tools
    for creating complex software in C++ to solve real world problems. See
    http://dlib.net for the main project documentation and API reference.

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
    - Tobias-Fischer
