{% set name = "dlib" %}
{% set version = "19.9" %}
{% set blas_variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/davisking/{{ name }}/archive/v{{ version }}.tar.gz
  sha1: 9ff9573dab29136e7157e71e81c26baff53254fa

  patches:
    - osx_jpeg.patch           # [osx]
    - lapack_sgetrf.patch      # [unix]
    - win_jpeg_png.patch       # [win]
    - win_release_flags.patch  # [win]

build:
  skip: True                   # [win and py<35]
  number: 0                    # [win]
  number: 200                  # [not win]
  features:                    # [not win]
    - blas_{{ blas_variant }}  # [not win]

requirements:
  build:
    - python
    - cmake
    - toolchain3
    - pkgconfig                    # [not win]
    - openblas 0.2.20|0.2.20.*     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]
    - numpy 1.8.*                  # [not (win and (py35 or py36))]
    - numpy 1.9.*                  # [win and py35]
    - numpy 1.11.*                 # [win and py36]
    - pybind11
    - jpeg 9*                      # [not win]
    - libpng >=1.6.32,<1.6.35
    - sqlite 3.20.*                # [not win]

  run:
    - python
    - openblas 0.2.20|0.2.20.*     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]
    - numpy 1.8.*                  # [not (win and (py35 or py36))]
    - numpy 1.9.*                  # [win and py35]
    - numpy 1.11.*                 # [win and py36]
    - jpeg 9*                      # [not win]
    - libpng >=1.6.32,<1.6.35
    - sqlite 3.20.*                # [not win]

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml

  requires:
    - tqdm
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost 1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms with Python bindings

extra:
  recipe-maintainers:
    - patricksnape
