{% set name = "dlib" %}
{% set version = "19.10" %}
{% set blas_variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/davisking/{{ name }}/archive/v{{ version }}.tar.gz
  sha1: 624722775d0ff8e4f26889bd7d1d980fcb096927

  patches:
    - osx_jpeg.patch           # [osx]
    - lapack_sgetrf.patch      # [unix]
    - win_jpeg_png.patch       # [win]
    - win_release_flags.patch  # [win]

build:
  skip: True                   # [win and py<35]
  number: 1
  number: 201
  features:                    # [not win]
    - blas_{{ blas_variant }}  # [not win]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - toolchain3
    - pkgconfig                    # [not win]
    - openblas                     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]
    - numpy                        # [not (win and (py35 or py36))]
    - numpy                        # [win and py35]
    - numpy                        # [win and py36]
    - pybind11
    - jpeg                         # [not win]
    - libpng
    - sqlite                       # [not win]

  run:
    - python
    - openblas                     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]
    - {{ pin_compatible('numpy') }}                 # [not (win and (py35 or py36))]
    - {{ pin_compatible('numpy') }}                 # [win and py35]
    - {{ pin_compatible('numpy') }}                # [win and py36]
    - jpeg                         # [not win]
    - libpng
    - sqlite                       # [not win]

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml

  requires:
    - tqdm
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost 1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms with Python bindings

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
