{% set name = "dlib" %}
{% set version = "19.20" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/davisking/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fc3f0986350e8e53aceadf95a71d2f413f1eedc469abda99a462cb528741d411

  patches:
    - lapack_sgetrf.patch      # [unix]
    - cxx11_detection.patch

build:
  skip: true  # [win and py<35]
  number: 1
  run_exports:
    - {{ pin_subpackage('dlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pybind11
    - liblapack   # [not win]
    - libcblas  # [not win]
    - numpy
    - jpeg
    - libpng
    - sqlite  # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml

  requires:
    - tqdm
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms with Python bindings

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
