{% set name = "dlib" %}
{% set version = "19.17" %}
{% set blas_variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/davisking/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9d2a158b2adad6acba2346f90d929558a691151aa076a0b409ee685534118692

  patches:
    - osx_jpeg.patch           # [osx]
    - lapack_sgetrf.patch      # [unix]
    - win_jpeg_png.patch       # [win]
    - win_release_flags.patch  # [win]

build:
  skip: True                   # [win and py<35]
  number: 200

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - pkgconfig                    # [not win]
  host:
    - libblas
    - libcblas
    - python
    - numpy
    - pybind11
    - jpeg                         # [not win]
    - libpng
    - sqlite                       # [not win]
  run:
    - python
    - {{ pin_compatible("numpy") }}
    - jpeg                         # [not win]
    - libpng
    - sqlite                       # [not win]

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml

  requires:
    - tqdm
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost 1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms with Python bindings

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
