{% set name = "dlib" %}
{% set version = "19.10" %}
{% set blas_variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/davisking/{{ name }}/archive/v{{ version }}.tar.gz
  sha1: 624722775d0ff8e4f26889bd7d1d980fcb096927

  patches:
    - osx_jpeg.patch           # [osx]
    - win_jpeg_png.patch       # [win]
    - win_release_flags.patch  # [win]

build:
  skip: True                   # [win and py<35]
  number: 1
  number: 201
  features:                    # [not win]

requirements:
  build:
    - libblas
    - libcblas
    - python
    - cmake
    - toolchain3
    - pkgconfig                    # [not win]
    - numpy 1.8.*                  # [not (win and (py35 or py36))]
    - numpy 1.9.*                  # [win and py35]
    - numpy 1.11.*                 # [win and py36]
    - pybind11
    - jpeg 9*                      # [not win]
    - libpng >=1.6.32,<1.6.35
    - sqlite 3.20.*                # [not win]

  run:
    - python
    - numpy >=1.8.*                # [not (win and (py35 or py36))]
    - numpy >=1.9.*                # [win and py35]
    - numpy >=1.11.*               # [win and py36]
    - jpeg 9*                      # [not win]
    - libpng >=1.6.32,<1.6.35
    - sqlite 3.20.*                # [not win]

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml

  requires:
    - tqdm
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost 1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms with Python bindings

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
