{% set name = "dlib" %}
{% set version = "19.17" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/davisking/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9d2a158b2adad6acba2346f90d929558a691151aa076a0b409ee685534118692

  patches:
    - lapack_sgetrf.patch      # [unix]
    #- win_jpeg_png.patch       # [win]
    #- win_release_flags.patch  # [win]
    - cxx11_detection.patch
    - external_deps.patch
    - msvc_no_static_runtime.patch

build:
  skip: True  # [win and py<35]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pybind11
    - liblapack   # [not win]
    - libcblas  # [not win]
    - numpy
    - jpeg
    - libpng
    - sqlite  # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - jpeg
    - libpng
    - sqlite  # [not win]

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml

  requires:
    - tqdm
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms with Python bindings

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
