conda_build:
  pkg_format: null
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  win: azure
  linux_aarch64: default
  osx_arm64: default
test: native_and_emulated
workflow_settings:
  free_disk_space: quick
  build_workspace_dir:
    - provider: azure
      os: win
      value: C:\\bld\\
