build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
conda_build:
  pkg_format: null
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  win: azure
test_on_native_only: true
