appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dzHtiPNEgpRNuGoJBJZaoTP5Mkb/9L1oxtkcqRf0bq2UNcnQCpP7JNzFVzzBI/rDPTmQbEvXWPHo4lAguicK6wOekS8mbYqdjZ+APLSNRMG5sK0y9BvX1qdy8wKZToWaHGZMGjjtCjPX4TrwNDhwGXD55MLb3/C0Vkyo6AH4X4KSU7oPZktsPk5Sc9N5U7ycOJt289W9XoyiVcBqZGNqtq81G6yz7o9vlWCEWaVoVw5Yn+VCye/8JSFeBK8HMNocZLnZ3eS1RDUrKrr7ZSGOjq0/KCI9C1c/34b9y6JSTOBhmB8fD7FJcwpf9VG9st92H36kI6I5GPKqaCeHCcpp9UvLDaorLt1QHT9ZHRSvRekzqN5B5k16OjQ0siewoOzQZgy/hwogNKZ7lZybsa15IWJ9LfAWPsEEBxzhIucQiMsk46b0u0WPWJgZZPHDR2OCVND2N9LlfFoCWKvneEyn2ota3swL+0q+nELB8i+MNPg/WAsyUXOUyLgHWYK15turVmLig8ciOMDuU/xx/vIzCl+yHAhwhXa00RWAweQ3+Mj74O1Pnts0WYuQ7HbnNVZYSsZ07a60pg8P8vD21c8lAEc0GjyaOlw8dUp2769cPAVqPocx5mxHwS26gerZHXQi98vyHxOUtbBWONBz+Of7ByNR0TmzE/5QG8D50o3eQ78=}
